/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CaLamViecCTDAO;
import Model.CaLamViecCT;
import Model.NhanVien;
import Model.SanPham;
import com.edysys.utils.Auth;
import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Label;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 *
 * @author ASUS
 */
public class ChamCong extends javax.swing.JFrame {

    /**
     * Creates new form ChamCong
     */
    public ChamCong() {
        initComponents();
        innit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbNgay = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JpnChamCong = new javax.swing.JPanel();

        setResizable(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("Chấm tất cả");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Vui lòng chấm công ngay khi vào ca");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Ngày:");

        jlbNgay.setFont(new java.awt.Font(".VnArial", 1, 16)); // NOI18N
        jlbNgay.setForeground(new java.awt.Color(153, 153, 255));
        jlbNgay.setText("\"Ngày\"");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout JpnChamCongLayout = new javax.swing.GroupLayout(JpnChamCong);
        JpnChamCong.setLayout(JpnChamCongLayout);
        JpnChamCongLayout.setHorizontalGroup(
            JpnChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        JpnChamCongLayout.setVerticalGroup(
            JpnChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(JpnChamCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlbNgay)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         for (CaLamViecCT caLamViecCT : List) {
         caLamViecCT.setThoiGianChamCong(LayTime());
         dao.updateTime(caLamViecCT);
         jpn_ChamCong1.getBtnChamCong().setLabel("đã chấm");
         jpn_ChamCong1.setEnabled(false);
         jpn_ChamCong2.getBtnChamCong().setLabel("đã chấm");
         jpn_ChamCong2.setEnabled(false);
         jpn_ChamCong3.getBtnChamCong().setLabel("đã chấm");
         jpn_ChamCong3.setEnabled(false);
         jpn_ChamCong4.getBtnChamCong().setLabel("đã chấm");
         jpn_ChamCong4.setEnabled(false);
         jpn_ChamCong5.getBtnChamCong().setLabel("đã chấm");
         jpn_ChamCong5.setEnabled(false);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnChamCong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbNgay;
    // End of variables declaration//GEN-END:variables
public void innit() {
        Image img1 = Toolkit.getDefaultToolkit().createImage("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\icon\\bird.png");
        this.setIconImage(img1);
        NhanVien nv = new NhanVien();
        nv = Auth.user;
        List = dao.selectByDateAndMaNV(LayNgay(), nv.getMaNV());
        this.JpnChamCong.setLayout(new GridLayout(List.size(), 1, 10, 10));
        jlbNgay.setText(LayNgay());
        for (CaLamViecCT caLamViecCT : List) {
            if (caLamViecCT.getMaCaLV().equalsIgnoreCase("CA1")) {

                this.JpnChamCong.add(jpn_ChamCong1);
                jpn_ChamCong1.getJlbChamCong().setText("CA1");
                if (caLamViecCT.getThoiGianChamCong() != null) {
                    jpn_ChamCong1.getBtnChamCong().setLabel("Đã chấm");
                    jpn_ChamCong1.getBtnChamCong().setEnabled(false);
                } else {

                    jpn_ChamCong1.getBtnChamCong().addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            jpn_ChamCong1.getBtnChamCong().setEnabled(false);
                            //chamCong1.setEnabled(false);
                            jpn_ChamCong1.getBtnChamCong().setLabel("Đã chấm");
                            caLamViecCT.setThoiGianChamCong(LayTime());
                            dao.updateTime(caLamViecCT);
                        }
                    });
                }
            } else if (caLamViecCT.getMaCaLV().equalsIgnoreCase("CA2")) {
                this.JpnChamCong.add(jpn_ChamCong2);
                jpn_ChamCong2.getJlbChamCong().setText("CA2");
                if (caLamViecCT.getThoiGianChamCong() != null) {
                    jpn_ChamCong2.getBtnChamCong().setLabel("Đã chấm");
                    jpn_ChamCong2.getBtnChamCong().setEnabled(false);
                } else {

                    jpn_ChamCong2.getBtnChamCong().addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            jpn_ChamCong2.getBtnChamCong().setEnabled(false);
                            //chamCong1.setEnabled(false);
                            jpn_ChamCong2.getBtnChamCong().setLabel("Đã chấm");
                            caLamViecCT.setThoiGianChamCong(LayTime());
                            dao.updateTime(caLamViecCT);
                        }
                    });
                }
            } else if (caLamViecCT.getMaCaLV().equalsIgnoreCase("CA3")) {
                jpn_ChamCong3.getJlbChamCong().setText("CA3");
                this.JpnChamCong.add(jpn_ChamCong3);
                if (caLamViecCT.getThoiGianChamCong() != null) {
                    jpn_ChamCong3.getBtnChamCong().setLabel("Đã chấm");
                    jpn_ChamCong3.getBtnChamCong().setEnabled(false);
                } else {

                    jpn_ChamCong3.getBtnChamCong().addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            jpn_ChamCong3.getBtnChamCong().setEnabled(false);
                            //chamCong1.setEnabled(false);
                            jpn_ChamCong3.getBtnChamCong().setLabel("Đã chấm");
                            caLamViecCT.setThoiGianChamCong(LayTime());
                            dao.updateTime(caLamViecCT);
                        }
                    });
                }
            } else if (caLamViecCT.getMaCaLV().equalsIgnoreCase("CA4")) {
                // this.JpnChamCong.add(chamCong4);
                this.JpnChamCong.add(jpn_ChamCong4);
                jpn_ChamCong4.getJlbChamCong().setText("CA4");
                if (caLamViecCT.getThoiGianChamCong() != null) {
                    jpn_ChamCong4.getBtnChamCong().setLabel("Đã chấm");
                    jpn_ChamCong4.getBtnChamCong().setEnabled(false);
                } else {

                    jpn_ChamCong4.getBtnChamCong().addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            jpn_ChamCong4.getBtnChamCong().setEnabled(false);
                            //chamCong1.setEnabled(false);
                            jpn_ChamCong4.getBtnChamCong().setLabel("Đã chấm");
                            caLamViecCT.setThoiGianChamCong(LayTime());
                            dao.updateTime(caLamViecCT);
                        }
                    });
                }
            } else if (caLamViecCT.getMaCaLV().equalsIgnoreCase("CA5")) {

                this.JpnChamCong.add(jpn_ChamCong5);
                jpn_ChamCong5.getJlbChamCong().setText("CA5");
                if (caLamViecCT.getThoiGianChamCong() != null) {
                    jpn_ChamCong5.getBtnChamCong().setLabel("Đã chấm");
                    jpn_ChamCong5.getBtnChamCong().setEnabled(false);
                } else {

                    jpn_ChamCong5.getBtnChamCong().addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            jpn_ChamCong5.getBtnChamCong().setEnabled(false);
                            //chamCong1.setEnabled(false);
                            jpn_ChamCong5.getBtnChamCong().setLabel("Đã chấm");
                            caLamViecCT.setThoiGianChamCong(LayTime());
                            dao.updateTime(caLamViecCT);
                        }
                    });
                }
            }
        }
    }
    List<CaLamViecCT> List = new ArrayList<>();
    CaLamViecCTDAO dao = new CaLamViecCTDAO();
    Button chamCong1 = new Button("Chấm Ca 1");

    Button chamCong2 = new Button("Chấm Ca 2");
    Button chamCong3 = new Button("Chấm Ca 3");
    Button chamCong4 = new Button("Chấm Ca 4");
    Button chamCong5 = new Button("Chấm Ca 5");
    Jpn_ChamCong jpn_ChamCong1 = new Jpn_ChamCong();
    Jpn_ChamCong jpn_ChamCong2 = new Jpn_ChamCong();
    Jpn_ChamCong jpn_ChamCong3 = new Jpn_ChamCong();
    Jpn_ChamCong jpn_ChamCong4 = new Jpn_ChamCong();
    Jpn_ChamCong jpn_ChamCong5 = new Jpn_ChamCong();

    public String LayNgay() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        return timeNow;
    }

    public String LayTime() {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        return timeNow;
    }
}
