/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.SanPhamDAO;
import Model.SanPham;
import com.edysys.utils.MsgBox;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Jpn_PhieuXuat extends javax.swing.JPanel {

    float tienThoi = 0;
    String maSo;
    SanPhamDAO spDAO = new SanPhamDAO();
    private ArrayList<SanPham> list = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    int[] row;
     private DefaultListModel listModel;
      ArrayList<SanPham> listTimKiem = new ArrayList<>();
    /**
     * Creates new form Jpn_PhieuXuat
     */
    public Jpn_PhieuXuat() {
        initComponents();
        txtBarcode.requestFocus();
        jpmMenuSeach.add(jpnSeach);
        txtTienMat.requestFocus();
        model = (DefaultTableModel) tblSach.getModel();
        tblSach.setModel(model);
        listModel = new DefaultListModel();
        JListSanPham.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnSeach = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JListSanPham = new javax.swing.JList<>();
        jpmMenuSeach = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPhaiThu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtTienMat = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jlbDaGiam = new javax.swing.JLabel();
        lblTienThoi = new javax.swing.JLabel();

        JListSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JListSanPham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JListSanPham.setForeground(new java.awt.Color(51, 153, 255));
        JListSanPham.setVisibleRowCount(35);
        JListSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListSanPhamMouseClicked(evt);
            }
        });
        JListSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JListSanPhamKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(JListSanPham);

        javax.swing.GroupLayout jpnSeachLayout = new javax.swing.GroupLayout(jpnSeach);
        jpnSeach.setLayout(jpnSeachLayout);
        jpnSeachLayout.setHorizontalGroup(
            jpnSeachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jpnSeachLayout.setVerticalGroup(
            jpnSeachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        jpmMenuSeach.setFocusable(false);

        setPreferredSize(new java.awt.Dimension(1143, 667));

        tblSach.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSach.setRowHeight(30);
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        tblSach.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblSachPropertyChange(evt);
            }
        });
        tblSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSachKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nhập mã sản phẩm (F8)");
        jLabel1.setOpaque(true);

        txtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeActionPerformed(evt);
            }
        });
        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Phải thu:");

        lblPhaiThu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPhaiThu.setForeground(new java.awt.Color(255, 102, 102));
        lblPhaiThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhaiThu.setText("0");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Tổng tiền:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Đã giảm:");

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiền mặt (F9)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txtTienMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienMatActionPerformed(evt);
            }
        });
        txtTienMat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTienMatPropertyChange(evt);
            }
        });
        txtTienMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienMatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienMatKeyReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Cà thẻ F7");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("PMH F4");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Tích điểm Ctrl + 2");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("In Bill F12");

        jButton12.setText("Ctrl + 2");

        jButton14.setText("F12");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("F4");

        jButton1.setText("F7");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTienMat)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jButton1))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jButton15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jButton14))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Tiền thối lại:");

        lblTongTien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien.setText("0");

        jlbDaGiam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbDaGiam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDaGiam.setText("0");

        lblTienThoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTienThoi.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPhaiThu)
                .addGap(42, 42, 42))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbDaGiam, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(64, 64, 64))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienThoi)
                .addGap(34, 34, 34))
            .addComponent(txtBarcode)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPhaiThu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlbDaGiam))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTienThoi))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblSachMouseClicked

    private void tblSachPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblSachPropertyChange
        // TODO add your handling code here:

        if (list.size() > 0) {
            int thaydoi = tblSach.getSelectedRow();
            System.out.println(tblSach.getValueAt(thaydoi, 2));
            int i = (int) tblSach.getValueAt(thaydoi, 2);
            list.get(thaydoi).setSoLuongBan(i);
            //  list.get(thaydoi).getThanhTien();
            // System.out.println("Đã thay đổi số lượng của sản phẩm " + list.get(thaydoi).getTenSP() + " bằng :" + tblSach.getValueAt(thaydoi, 2));
        }
        FillToTable();
    }//GEN-LAST:event_tblSachPropertyChange

    private void tblSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSachKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblSachKeyPressed

    private void txtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarcodeActionPerformed

    private void txtBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getSanPham(txtBarcode.getText());
            txtBarcode.setText("");
            
        }
    }//GEN-LAST:event_txtBarcodeKeyPressed

    private void txtTienMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienMatActionPerformed

    private void txtTienMatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTienMatPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienMatPropertyChange

    private void txtTienMatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienMatKeyPressed

    private void txtTienMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienMatKeyReleased
        // TODO add your handling code here:
        if(list.size()>0){
        try {
            if (Float.parseFloat(txtTienMat.getText()) >= LayTongTien()) {
                tienThoi = Float.parseFloat(txtTienMat.getText()) - LayTongTien();
                lblTienThoi.setText(tienThoi + " VND");
            } else {
                lblTienThoi.setText("0");
            }
        } catch (NumberFormatException e) {
            lblTienThoi.setText("0");
        }}
    }//GEN-LAST:event_txtTienMatKeyReleased
    public ArrayList<SanPham> getList() {
        return this.list;
    }
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void JListSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListSanPhamMouseClicked
        // TODO add your handling code here:

        int index = JListSanPham.getSelectedIndex();
        SanPham sanPham = new SanPham();
        sanPham = listTimKiem.get(index);
        getSanPham(sanPham.getBarcode());
        txtBarcode.setText("");
        txtBarcode.requestFocus();
        FillToTable();
    }//GEN-LAST:event_JListSanPhamMouseClicked

    private void JListSanPhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JListSanPhamKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int index = JListSanPham.getSelectedIndex();
            SanPham sanPham = new SanPham();
            sanPham = listTimKiem.get(index);
            getSanPham(sanPham.getBarcode());
            txtBarcode.setText("");
            txtBarcode.requestFocus();
            FillToTable();
        }
    }//GEN-LAST:event_JListSanPhamKeyPressed

    private void txtBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyReleased
        // TODO add your handling code here
        String text = txtBarcode.getText();
        System.out.println("View.Jpn_PhieuXuat.txtBarcodeKeyReleased()");
        if (!text.equals("")) {
            listModel.removeAllElements();
            listTimKiem.removeAll(listTimKiem);
            List<SanPham> sp = new ArrayList<>();
            try {
                Integer.parseInt(text);
                sp = spDAO.selectBykeyBarcode(text);
                for (SanPham sanPham : sp) {
                    listTimKiem.add(sanPham);
                    listModel.addElement(sanPham.getTenSP());
                }
                jpmMenuSeach.show(txtBarcode, 0, txtBarcode.getHeight());
            } catch (Exception e) {
                listTimKiem.removeAll(listTimKiem);
                sp = spDAO.selectBykeyWork(text);
                for (SanPham sanPham : sp) {
                    listTimKiem.add(sanPham);
                    listModel.addElement(sanPham.getTenSP());
                }
                jpmMenuSeach.show(txtBarcode, 0, txtBarcode.getHeight());
            }
        } else {
            jpmMenuSeach.setVisible(false);
        }
    }//GEN-LAST:event_txtBarcodeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListSanPham;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel jlbDaGiam;
    private javax.swing.JPopupMenu jpmMenuSeach;
    private javax.swing.JPanel jpnSeach;
    private javax.swing.JLabel lblPhaiThu;
    private javax.swing.JLabel lblTienThoi;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtTienMat;
    // End of variables declaration//GEN-END:variables
    public void ResetMBH(){
    list.removeAll(list);
    FillToTable();
    lblTongTien.setText("0");
    lblTienThoi.setText("0");
    lblPhaiThu.setText("0");
    jlbDaGiam.setText("0");
    txtBarcode.requestFocus();
    txtTienMat.setText("");
    }
    public void getSanPham(String barcode) {

        SanPham sp = new SanPham();
        sp = spDAO.selectById(barcode);
        if (sp == null) {
            MsgBox.alert(this, "Sản phẩm không tồn tại, vui lòng kiểm tra lại mã sản phẩm!");
        } else {
            for (SanPham sanPham : list) {
                if (sp.getBarcode().equals(sanPham.getBarcode())) {
                    sanPham.setSoLuongBan(sanPham.getSoLuongNew());
                    FillToTable();
                    LayTongTien();
                    return;
                }
            }
            list.add(sp);
            FillToTable();
            LayTongTien();

        }
    }

    public void FillToTable() {
        int STT = 1;
        model.setRowCount(0);
        int TongTien = 0;
        for (SanPham sp : list) {
            model.addRow(new Object[]{STT, sp.getTenSP(), sp.getSoLuongBan(), sp.getDonGia(), sp.getThanhTien()});
            STT++;
        }
        LayTongTien();
    }

    public Float LayTongTien() {
        float tongTien = 0;
        for (SanPham sanPham : list) {
            tongTien = tongTien + sanPham.getThanhTien();
        }
        lblPhaiThu.setText(String.valueOf(tongTien));
        lblTongTien.setText(String.valueOf(tongTien));
        return tongTien;
    }
    public boolean CheckTienMat(){
    if(txtTienMat.equals("") || Float.parseFloat(lblPhaiThu.getText())>Float.parseFloat(txtTienMat.getText())){
    return false;
    }
    else{
    return true;}   
    }
//     public void InHOaDon() {
//        System.out.println("Bắt đầu tạo hóa đơn!");
//        // Tao MaHD
//        maSo = "";
//        DateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");
//        Calendar cal = Calendar.getInstance();
//        String timeNow = dateFormat.format(cal.getTime());
//        //timeNow = timeNow.substring(2,13);
//        maSo = maSo + timeNow;
//        System.out.println("View.View_MBH.InHOaDon()" + maSo);
//        // Tao HD
//        HoaDon hd = new HoaDon(maSo, Auth.user.getMaNV(), LayThoiGian(), Float.parseFloat(txtTienMat.getText()), tienThoi, LayTongTien());
//        hdDAO.insert(hd);
//        // TaoHDCT
//        for (SanPham sanPham : list) {
//            HoaDonCT hdct = new HoaDonCT(maSo, sanPham.getBarcode(), sanPham.getSoLuongBan(), sanPham.getThanhTien());
//            hdctDAO.insert(hdct);
//        }
//        xuatBill();
//    }
}
