/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CaLamViecCTDAO;
import DAO.NhanVienDAO;
import Model.CaLamViecCT;
import Model.NhanVien;
import Model.SanPham;
import com.edysys.utils.Auth;
import com.edysys.utils.MsgBox;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuangLyCH extends javax.swing.JFrame {

    DefaultTableModel modelNV = new DefaultTableModel();
    List<NhanVien> list = new ArrayList<>();
    List<CaLamViecCT> listCaLvCT = new ArrayList<>();

    /**
     * Creates new form QuangLyCH
     */
    public QuangLyCH() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelNV = (DefaultTableModel) jtbPhanCa.getModel();
        jtbPhanCa.setModel(modelNV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPhanCa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JclNgayPhanCa = new com.toedter.calendar.JDateChooser();
        btnXemLicPc = new javax.swing.JButton();
        btnLuuLichPc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setOpaque(true);

        jtbPhanCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên + User", "Ca 1 (5)", "Ca 2 (2)", "Ca 3 (2)", "Ca 4 (2)", "Ca 5 (3.5)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPhanCa.setRowHeight(30);
        jScrollPane1.setViewportView(jtbPhanCa);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Ngày phân ca:");

        JclNgayPhanCa.setDateFormatString("yyyy-MM-dd");

        btnXemLicPc.setText("Xem");
        btnXemLicPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLicPcActionPerformed(evt);
            }
        });

        btnLuuLichPc.setText("Lưu lịch phân ca");
        btnLuuLichPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLichPcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JclNgayPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXemLicPc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuLichPc)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JclNgayPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXemLicPc)
                        .addComponent(btnLuuLichPc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Quản lý phân ca", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Xác nhận chấm công", jPanel2);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("In thẻ nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(843, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Tìm nhân viên", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê doanh thu", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //FillToTablePhanCa();
    }//GEN-LAST:event_formWindowOpened

    private void btnXemLicPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLicPcActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(JclNgayPhanCa.getDate());
            //calvCTDAO.selectById(date)
            listCaLvCT = calvCTDAO.selectByDate(date);
            if (listCaLvCT == null) {
                MsgBox.alert(this, "Ngày " + date + " chưa có ca làm việc!");
                FillToTablePhanCa();
            } else {
                list = nvDAO.selectAll();
                modelNV.setRowCount(0);
                for (NhanVien nhanVien : list) {
                    modelNV.addRow(new Object[]{nhanVien.getHoTenNV() + "-" + nhanVien.getMaNV(), calvCTDAO.KiemTraCaLam(date, "CA1", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA2", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA3", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA4", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA5", nhanVien.getMaNV())});
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Hãy lựa chọn ngày phân ca!");
        }
    }//GEN-LAST:event_btnXemLicPcActionPerformed

    private void btnLuuLichPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLichPcActionPerformed
        // TODO add your handling code here:
//        boolean check = true;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(JclNgayPhanCa.getDate());
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        SimpleDateFormat spf = new SimpleDateFormat("yyyy-MM-dd");
        listCaLvCT = calvCTDAO.selectByDate(date);
        try {
            Date toDay = spf.parse(timeNow);
            Date viewDay = spf.parse(date);
            System.out.println(viewDay.compareTo(toDay));
            if (viewDay.compareTo(toDay) < 0) {
//                check = false;
                MsgBox.alert(this, "Không thể chỉnh sửa lịch phân ca trong quá khứ!");
            }
//            else if((viewDay.compareTo(toDay) ==0 || viewDay.compareTo(toDay) >0) && listCaLvCT.size()>0){
//             for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
//            for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
//                if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
//                    NhanVien nv = new NhanVien();
//                    nv = list.get(j);
//                    CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
//                    System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed()update");
//                    calvCTDAO.update(caLvCT);
//                }
//            }
//           
//        }
//              MsgBox.alert(this, "Lưu thành công");
//            }
            else{
               
            for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
            for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                    NhanVien nv = new NhanVien();
                    nv = list.get(j);

                    CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                    System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                    calvCTDAO.insert(caLvCT);

                }
//if(jtbPhanCa.getValueAt(i,j)==jtbPhanCa.getValueAt(i,j+1)){}

            }
           
        }
             MsgBox.alert(this, "Lưu thành công");
            }
        } catch (ParseException ex) {
            Logger.getLogger(QuangLyCH.class.getName()).log(Level.SEVERE, null, ex);
        }

//

        
    }//GEN-LAST:event_btnLuuLichPcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            new QuangLyCH().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JclNgayPhanCa;
    private javax.swing.JButton btnLuuLichPc;
    private javax.swing.JButton btnXemLicPc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbPhanCa;
    // End of variables declaration//GEN-END:variables
// In the nhan vien
    NhanVienDAO nvDAO = new NhanVienDAO();
    CaLamViecCTDAO calvCTDAO = new CaLamViecCTDAO();

    public void FillToTablePhanCa() {
        list = nvDAO.selectAll();
        System.out.println("View.QuangLyCH.FillToTablePhanCa()" + list.size());
        modelNV.setRowCount(0);
        for (NhanVien nhanVien : list) {
            modelNV.addRow(new Object[]{nhanVien.getHoTenNV() + "-" + nhanVien.getMaNV(), false, false, false, false, false});
        }

    }
}
