/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author ASUS
 */
public class View_TBHH_ChamHang extends javax.swing.JPanel {

    /**
     * Creates new form Jpn_ViTriHangHoa
     */
    public View_TBHH_ChamHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbHa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbSoKe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbTenSP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbViTriSp = new javax.swing.JLabel();
        jlbSoLuongTb = new javax.swing.JLabel();
        jlbTonKho = new javax.swing.JLabel();
        jlbBarcode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbGiaSp1 = new javax.swing.JLabel();
        btnInTemGia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlbSoLuongCanCham = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jlbHa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbHa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Số kệ: ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Giá bán:");

        jlbSoKe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbSoKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSoKe.setText("0");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Tồn tại cửa hàng:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Vị trí:");

        jlbTenSP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbTenSP.setText("Tên sản phẩm");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 102, 255));
        jLabel8.setText("Số lượng trưng bày:");

        jlbViTriSp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbViTriSp.setForeground(new java.awt.Color(255, 153, 51));
        jlbViTriSp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbViTriSp.setText("0");

        jlbSoLuongTb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbSoLuongTb.setForeground(new java.awt.Color(153, 153, 255));
        jlbSoLuongTb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSoLuongTb.setText("0");

        jlbTonKho.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbTonKho.setForeground(new java.awt.Color(0, 102, 0));
        jlbTonKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTonKho.setText("0");

        jlbBarcode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbBarcode.setText("0");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Barcode:");

        jlbGiaSp1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbGiaSp1.setForeground(new java.awt.Color(255, 51, 102));
        jlbGiaSp1.setText("0");

        btnInTemGia.setText("Châm hàng");
        btnInTemGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInTemGiaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng cần châm:");

        jlbSoLuongCanCham.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbSoLuongCanCham.setForeground(new java.awt.Color(102, 153, 255));
        jlbSoLuongCanCham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSoLuongCanCham.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbTenSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlbSoKe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlbViTriSp, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlbSoLuongTb, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbSoLuongCanCham, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(379, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbGiaSp1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInTemGia)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlbSoKe)
                            .addComponent(jLabel6)
                            .addComponent(jlbViTriSp)
                            .addComponent(jLabel8)
                            .addComponent(jlbSoLuongTb)
                            .addComponent(jLabel5)
                            .addComponent(jlbTonKho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbTenSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbGiaSp1)
                            .addComponent(btnInTemGia)
                            .addComponent(jLabel4)
                            .addComponent(jlbSoLuongCanCham))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlbBarcode)))
                    .addComponent(jlbHa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInTemGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInTemGiaActionPerformed
        // TODO add your handling code here:
        InTemaGiaSanPham();
    }//GEN-LAST:event_btnInTemGiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInTemGia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlbBarcode;
    private javax.swing.JLabel jlbGiaSp1;
    private javax.swing.JLabel jlbHa;
    private javax.swing.JLabel jlbSoKe;
    private javax.swing.JLabel jlbSoLuongCanCham;
    private javax.swing.JLabel jlbSoLuongTb;
    private javax.swing.JLabel jlbTenSP;
    private javax.swing.JLabel jlbTonKho;
    private javax.swing.JLabel jlbViTriSp;
    // End of variables declaration//GEN-END:variables
public void setSoKe(String soKe){
jlbSoKe.setText(soKe);}


public void setViTri(String viTri){
jlbViTriSp.setText(viTri);}

public void setSoLuongTB(String soLuongTB){
jlbSoLuongTb.setText(soLuongTB);}


public void setTonTaiCH(String tonTaiCH){
jlbTonKho.setText(tonTaiCH);
}


public void setTenSanPham(String tenSanPham){

jlbTenSP.setText(tenSanPham);
        }


public void setGiaBan(String giaBan){
jlbGiaSp1.setText(giaBan);}


public void setBarcode(String barcode){
jlbBarcode.setText(barcode);}
public void setImage(String sRc){

        // btnHa.setIcon(imc);
       ImageIcon imc = new ImageIcon(sRc);
        System.out.println(sRc);
        // btnHa.setIcon(imc);
        Image img = imc.getImage();
        System.out.println("View.Jpn_ViTriHangHoa.setImage()s");
        Image newImg = img.getScaledInstance(68, 106, Image.SCALE_SMOOTH);
        System.out.println("View.Jpn_ViTriHangHoa.setImage()h");
        ImageIcon icon = new ImageIcon(newImg);
        jlbHa.setIcon(icon);
}
public void InTemaGiaSanPham(){
    
            try {
                Hashtable map = new Hashtable();
                JasperReport rpt = JasperCompileManager.compileReport("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\Report\\TeamGia.jrxml");
                map.put("Barcode", jlbBarcode.getText());
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TGSTeam", "sa", "123");
                JasperPrint p = JasperFillManager.fillReport(rpt, map, conn);
                // JasperViewer.viewReport(p, false); // Hiển thị file PDF
                JasperPrintManager.printReport(p, false);// Gửi Report đến máy in    
            } catch (JRException ex) {
                Logger.getLogger(View_Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(View_Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}
