package View;

import DAO.CaLamViecCTDAO;
import DAO.MamTrungBayDAO;
import DAO.SanPhamDAO;
import Model.CaLamViecCT;
import Model.MamTrungBay;
import Model.NhanVien;
import Model.SanPham;
import com.edysys.utils.Auth;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class View_TBHH extends javax.swing.JFrame {

    DefaultTableModel modelTemGia = new DefaultTableModel();
    private ArrayList<SanPham> listTemGia = new ArrayList<>();
    /**
     * Creates new form TBHH
     */
    CardLayout card = new CardLayout();
    
    public View_TBHH() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Image img1 = Toolkit.getDefaultToolkit().createImage("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\icon\\bird.png");
        this.setIconImage(img1);
        this.jpnCard.setLayout(card);
        this.setLocationRelativeTo(null);
        modelTemGia = (DefaultTableModel) jtblInTemGia.getModel();
        jtblInTemGia.setModel(modelTemGia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jdlInTemGia = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblInTemGia = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtBarcode = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jdlKiemKe = new javax.swing.JDialog();
        jlbHinhAnh = new javax.swing.JLabel();
        jlbTenSP = new javax.swing.JLabel();
        jlbTenSP1 = new javax.swing.JLabel();
        jlbSoKe = new javax.swing.JLabel();
        jlbTenSP3 = new javax.swing.JLabel();
        jlbSoMam = new javax.swing.JLabel();
        jlbTenSP5 = new javax.swing.JLabel();
        jlbViTri = new javax.swing.JLabel();
        jlbTenSP7 = new javax.swing.JLabel();
        jlbTonKho = new javax.swing.JLabel();
        jlbTenSP9 = new javax.swing.JLabel();
        jlbDonGia = new javax.swing.JLabel();
        jlbTenSP11 = new javax.swing.JLabel();
        jlbBarcode = new javax.swing.JLabel();
        jlbTenSP13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jlbTenSP15 = new javax.swing.JLabel();
        txtDonViLoc = new javax.swing.JTextField();
        jlbTenSP16 = new javax.swing.JLabel();
        txtDonViCai = new javax.swing.JTextField();
        txt_jdl_barcode = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jlbViTri1 = new javax.swing.JLabel();
        jlbTrungBay = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jpnCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jtblInTemGia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtblInTemGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblInTemGia.setGridColor(new java.awt.Color(153, 204, 255));
        jtblInTemGia.setRowHeight(20);
        jScrollPane1.setViewportView(jtblInTemGia);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyPressed(evt);
            }
        });

        jButton5.setText("In");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdlInTemGiaLayout = new javax.swing.GroupLayout(jdlInTemGia.getContentPane());
        jdlInTemGia.getContentPane().setLayout(jdlInTemGiaLayout);
        jdlInTemGiaLayout.setHorizontalGroup(
            jdlInTemGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdlInTemGiaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jdlInTemGiaLayout.setVerticalGroup(
            jdlInTemGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlInTemGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
        );

        jdlKiemKe.setBackground(new java.awt.Color(255, 255, 255));
        jdlKiemKe.setModal(true);

        jlbHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbTenSP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP.setText("\"Tên sản phẩm\"");

        jlbTenSP1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP1.setText("Kệ:");

        jlbSoKe.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbSoKe.setText("0");

        jlbTenSP3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP3.setText("Mâm:");

        jlbSoMam.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbSoMam.setText("0");

        jlbTenSP5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP5.setText("Vị trí:");

        jlbViTri.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbViTri.setText("0");

        jlbTenSP7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP7.setText("Tồn kho:");

        jlbTonKho.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTonKho.setText("0");

        jlbTenSP9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP9.setText("Giá bán:");

        jlbDonGia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbDonGia.setText("0");

        jlbTenSP11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP11.setText("Barcode:");

        jlbBarcode.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbBarcode.setText("\"barCode\"");

        jlbTenSP13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP13.setText("Cập nhật tồn kho:");

        jButton6.setText("Lưu");

        jButton7.setText("Thoát");

        jlbTenSP15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP15.setText("Đơn vị (Cái):");

        txtDonViLoc.setText("\"0\"");

        jlbTenSP16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTenSP16.setText("Đơn vị (Lốc 10):");

        txtDonViCai.setText("\"0\"");

        txt_jdl_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jdl_barcodeActionPerformed(evt);
            }
        });

        jButton8.setText("Tìm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jlbViTri1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbViTri1.setText("Trưng bày:");

        jlbTrungBay.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbTrungBay.setText("0");

        javax.swing.GroupLayout jdlKiemKeLayout = new javax.swing.GroupLayout(jdlKiemKe.getContentPane());
        jdlKiemKe.getContentPane().setLayout(jdlKiemKeLayout);
        jdlKiemKeLayout.setHorizontalGroup(
            jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlKiemKeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdlKiemKeLayout.createSequentialGroup()
                                .addComponent(jlbTenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbSoKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlbTenSP3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbSoMam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlbTenSP5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(175, Short.MAX_VALUE))
                            .addGroup(jdlKiemKeLayout.createSequentialGroup()
                                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdlKiemKeLayout.createSequentialGroup()
                                                .addComponent(jlbTenSP9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdlKiemKeLayout.createSequentialGroup()
                                                .addComponent(jlbTenSP7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlbTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jlbViTri1)))
                                        .addGap(51, 51, 51)
                                        .addComponent(jlbTrungBay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                                        .addComponent(jlbTenSP11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(121, Short.MAX_VALUE))))
                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTenSP16)
                            .addComponent(jlbTenSP15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdlKiemKeLayout.createSequentialGroup()
                                .addComponent(txtDonViCai, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addGap(386, 386, 386))
                            .addGroup(jdlKiemKeLayout.createSequentialGroup()
                                .addComponent(txtDonViLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                        .addComponent(jlbTenSP13)
                        .addContainerGap())))
            .addGroup(jdlKiemKeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txt_jdl_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdlKiemKeLayout.setVerticalGroup(
            jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlKiemKeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jdl_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdlKiemKeLayout.createSequentialGroup()
                        .addComponent(jlbTenSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbSoKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbTenSP3)
                                .addComponent(jlbSoMam)
                                .addComponent(jlbTenSP5)
                                .addComponent(jlbViTri)
                                .addComponent(jlbTenSP1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbTonKho)
                                .addComponent(jlbViTri1)
                                .addComponent(jlbTrungBay))
                            .addComponent(jlbTenSP7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(1, 1, 1)
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTenSP11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbBarcode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTenSP9)
                            .addComponent(jlbDonGia)))
                    .addComponent(jlbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbTenSP13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonViCai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTenSP15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTenSP16)
                    .addComponent(txtDonViLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jdlKiemKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Home");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Trưng bày hàng hóa");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("In tem giá");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Kiểm kê theo khu");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jpnCard.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bird.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jpnCard.add(jLabel1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu2.setText("Chức năng hệ thống");

        jMenuItem6.setText("Home");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Trưng bày hàng hóa");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Kiểm kê theo khu");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("In tem giá");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Chức năng khác");

        jMenuItem2.setText("Lịch sử chấm công");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Lịch phân ca cá nhân");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Lịch phân ca cửa hàng");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setText("Đăng xuất");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) this.getContentPane().getLayout();
        cardLayout.first(this.getContentPane());

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            jpnCard.add(new Tbhh_Jpn(), "Add");
        } catch (Exception e) {
            System.out.println(e);
        }
        
        card.show(jpnCard, "Add");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) this.jpnCard.getLayout();
        cardLayout.first(this.jpnCard);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        NhanVien nv = new NhanVien();
        nv = Auth.user;
        // Hiển thị tên nhân viên ở Bottom màng hình

        /*
       - Hiển thị form chấm công
       + điều kiện 1: Nhân viên có ca làm việc
       + điều kiện 2: nhân viên có ca chưa chấm
         */
        // Giải quyết diều kiện 1: Tìm kiếm CaLamViecCT với diều 2 tham số (MaNV,Ngay), kết quả khác null => Nhân viên có ca làm việc
        // Giải quyết điều kiện 2: Lấy ThoiGianChamCong nếu trả về null => nhân viên chưa chấm công
        CaLamViecCTDAO dao = new CaLamViecCTDAO();
        List<CaLamViecCT> list = new ArrayList<>();
        list = dao.selectByDateAndMaNV(LayNgay(), nv.getMaNV());
        if (list.size() > 0) {
            for (CaLamViecCT caLamViecCT : list) {
                if (caLamViecCT.getThoiGianChamCong() == null) {
                    ChamCong chamCong_View = new ChamCong();
                    try {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                        chamCong_View.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                    };
                    chamCong_View.setLocationRelativeTo(null);
                    return;
                }
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        View_LichSuChamCong view_LichSuChamCong = new View_LichSuChamCong();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            view_LichSuChamCong.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.jdlInTemGia.setVisible(true);
        this.jdlInTemGia.setLocationRelativeTo(null);
        this.jdlInTemGia.setSize(319, 440);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void txtBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getSanPham();
            txtBarcode.setText("");
            
        }
    }//GEN-LAST:event_txtBarcodeKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        for (SanPham sp : listTemGia) {
            try {
                Hashtable map = new Hashtable();
                JasperReport rpt = JasperCompileManager.compileReport("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\Report\\TeamGia.jrxml");
                map.put("Barcode", sp.getBarcode());
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=TGSTeam", "sa", "123");
                JasperPrint p = JasperFillManager.fillReport(rpt, map, conn);
                // JasperViewer.viewReport(p, false); // Hiển thị file PDF
                JasperPrintManager.printReport(p, false);// Gửi Report đến máy in    
            } catch (JRException ex) {
                Logger.getLogger(View_Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(View_Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        listTemGia.removeAll(listTemGia);
        modelTemGia.setRowCount(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_jdl_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jdl_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jdl_barcodeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jdlKiemKe.setSize(542, 400);
        jdlKiemKe.setLocationRelativeTo(null);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
           jdlKiemKe.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        jdlKiemKe.setVisible(true);
         
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        getSanPhamKiemKe();
        txt_jdl_barcode.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        LichPhanCaCaNhan lichPhanCaCaNhan;
        try {
            lichPhanCaCaNhan = new LichPhanCaCaNhan();
            lichPhanCaCaNhan.setLocationRelativeTo(this);
            try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            new LichPhanCaCaNhan().setVisible(true)
                    ;
           
        } catch (Exception e) {
            e.printStackTrace();
        };
        } catch (ParseException ex) {
            Logger.getLogger(View_TBHH.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_TBHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_TBHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_TBHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_TBHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            new View_TBHH().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jdlInTemGia;
    private javax.swing.JDialog jdlKiemKe;
    private javax.swing.JLabel jlbBarcode;
    private javax.swing.JLabel jlbDonGia;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JLabel jlbSoKe;
    private javax.swing.JLabel jlbSoMam;
    private javax.swing.JLabel jlbTenSP;
    private javax.swing.JLabel jlbTenSP1;
    private javax.swing.JLabel jlbTenSP11;
    private javax.swing.JLabel jlbTenSP13;
    private javax.swing.JLabel jlbTenSP15;
    private javax.swing.JLabel jlbTenSP16;
    private javax.swing.JLabel jlbTenSP3;
    private javax.swing.JLabel jlbTenSP5;
    private javax.swing.JLabel jlbTenSP7;
    private javax.swing.JLabel jlbTenSP9;
    private javax.swing.JLabel jlbTonKho;
    private javax.swing.JLabel jlbTrungBay;
    private javax.swing.JLabel jlbViTri;
    private javax.swing.JLabel jlbViTri1;
    private javax.swing.JPanel jpnCard;
    private javax.swing.JTable jtblInTemGia;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtDonViCai;
    private javax.swing.JTextField txtDonViLoc;
    private javax.swing.JTextField txt_jdl_barcode;
    // End of variables declaration//GEN-END:variables
    SanPhamDAO sanPhamDAO = new SanPhamDAO();
    MamTrungBayDAO mamTrungBayDAO = new MamTrungBayDAO();
    public String LayNgay() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        return timeNow;
    }
    
    private void getSanPham() {
        SanPham sanPham = new SanPham();
        sanPham = sanPhamDAO.selectById(txtBarcode.getText());
        listTemGia.add(sanPham);
        modelTemGia.setRowCount(0);
        for (SanPham sanPham1 : listTemGia) {
            modelTemGia.addRow(new Object[]{sanPham.getTenSP(), sanPham.getDonGia()});
        }
        
    }

    private void getSanPhamKiemKe() {
          String URL = "C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\";
        MamTrungBay mamTrungBay = new MamTrungBay();
        mamTrungBay = mamTrungBayDAO.selectByBarcode(txt_jdl_barcode.getText());
        SanPham sp = new SanPham();
        sp = sanPhamDAO.selectById(txt_jdl_barcode.getText());
        jlbTenSP.setText(sp.getTenSP());
        jlbSoKe.setText(mamTrungBay.getSoKe()+"");
        jlbSoMam.setText(mamTrungBay.getSoMam()+"");
        jlbViTri.setText(mamTrungBay.getViTri()+"");
        jlbTrungBay.setText(mamTrungBay.getTrungBay()+"");
        String sRcData = sp.getHinhAnh();
        jlbDonGia.setText(sp.getDonGia()+"");
        jlbBarcode.setText(sp.getBarcode());
         String sRc = URL + sRcData;
            sRcData = sRcData.replace('/', '\\');
            setImage(sRc);
            
    }
    public void setImage(String sRc){
        // btnHa.setIcon(imc);
       ImageIcon imc = new ImageIcon(sRc);
        System.out.println(sRc);
        // btnHa.setIcon(imc);
        Image img = imc.getImage();
        System.out.println("View.Jpn_ViTriHangHoa.setImage()s");
        Image newImg = img.getScaledInstance(68, 106, Image.SCALE_SMOOTH);
        System.out.println("View.Jpn_ViTriHangHoa.setImage()h");
        ImageIcon icon = new ImageIcon(newImg);
        jlbHinhAnh.setIcon(icon);
}
}
