/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CaLamViecCTDAO;
import DAO.CaLamViecDAO;
import DAO.NhanVienDAO;
import Model.CaLamViec;
import Model.CaLamViecCT;
import Model.NhanVien;
import Model.SanPham;
import com.edysys.utils.Auth;
import com.edysys.utils.MsgBox;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class View_QuangLyCH extends javax.swing.JFrame {

    DefaultTableModel modelNV = new DefaultTableModel();
    DefaultTableModel modelCaChoXn = new DefaultTableModel();
    List<NhanVien> list = new ArrayList<>();
    List<CaLamViecCT> listCaLvCT = new ArrayList<>();
    List<CaLamViecCT>  dScaChoXn= new ArrayList<>();
    /**
     * Creates new form QuangLyCH
     */
    public View_QuangLyCH() {
        initComponents();
        Image img1 = Toolkit.getDefaultToolkit().createImage("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\icon\\bird.png");
        this.setIconImage(img1);
        this.setLocationRelativeTo(null);
        modelNV = (DefaultTableModel) jtbPhanCa.getModel();
        jtbPhanCa.setModel(modelNV);
        modelCaChoXn = (DefaultTableModel) jtbChoXacNhanCong.getModel();
        jtbChoXacNhanCong.setModel(modelCaChoXn);
       // FillToTableCaChoXn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPhanCa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JclNgayPhanCa = new com.toedter.calendar.JDateChooser();
        btnXemLicPc = new javax.swing.JButton();
        btnLuuLichPc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbChoXacNhanCong = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBatDau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTgKetThuc = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtTgChamCong = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnXacNhanDung = new javax.swing.JButton();
        btnXacNhanSai = new javax.swing.JButton();
        txtCalamViec = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setOpaque(true);

        jtbPhanCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên + User", "Ca 1 (5)", "Ca 2 (2)", "Ca 3 (2)", "Ca 4 (2)", "Ca 5 (3.5)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPhanCa.setRowHeight(30);
        jtbPhanCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPhanCaMouseClicked(evt);
            }
        });
        jtbPhanCa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbPhanCaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPhanCa);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Ngày phân ca:");

        JclNgayPhanCa.setDateFormatString("yyyy-MM-dd");

        btnXemLicPc.setText("Xem");
        btnXemLicPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLicPcActionPerformed(evt);
            }
        });

        btnLuuLichPc.setText("Lưu lịch phân ca");
        btnLuuLichPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLichPcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JclNgayPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXemLicPc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuLichPc)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JclNgayPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXemLicPc)
                        .addComponent(btnLuuLichPc)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý phân ca", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("Chú ý: Vui lòng xác nhận chính xác, nghiêm cấm hành vi gian lận ");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yều cầu chờ xác nhận!", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jtbChoXacNhanCong.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtbChoXacNhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nhân viên", "Ca", "Thời gian chấm công"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbChoXacNhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbChoXacNhanCongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbChoXacNhanCong);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xác nhận công!", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ca làm việc:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ghi chú:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Thời gian chấm công:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Bắt đầu:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Kết thúc:");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        txtGhiChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGhiChuMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(txtGhiChu);

        btnXacNhanDung.setText("Xác nhận đúng");

        btnXacNhanSai.setText("Xác nhận sai");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCalamViec))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtTgChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(248, 248, 248))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTgKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnXacNhanDung)
                        .addGap(48, 48, 48)
                        .addComponent(btnXacNhanSai, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTgKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTgChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhanDung)
                    .addComponent(btnXacNhanSai))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Xác nhận chấm công", jPanel2);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("In thẻ nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(843, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Tìm nhân viên", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê doanh thu", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //FillToTablePhanCa();
    }//GEN-LAST:event_formWindowOpened

    private void btnXemLicPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLicPcActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(JclNgayPhanCa.getDate());
            //calvCTDAO.selectById(date)
            listCaLvCT = calvCTDAO.selectByDate(date);
            if (listCaLvCT == null) {
                MsgBox.alert(this, "Ngày " + date + " chưa có ca làm việc!");
                FillToTablePhanCa();
            } else {
                list = nvDAO.selectAll();
                modelNV.setRowCount(0);
                for (NhanVien nhanVien : list) {
                    modelNV.addRow(new Object[]{nhanVien.getHoTenNV() + "-" + nhanVien.getMaNV(), calvCTDAO.KiemTraCaLam(date, "CA1", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA2", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA3", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA4", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA5", nhanVien.getMaNV())});
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Hãy lựa chọn ngày phân ca!");
        }
    }//GEN-LAST:event_btnXemLicPcActionPerformed

    private void btnLuuLichPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLichPcActionPerformed
        // TODO add your handling code here:
//        boolean check = true;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(JclNgayPhanCa.getDate());
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        SimpleDateFormat spf = new SimpleDateFormat("yyyy-MM-dd");
        listCaLvCT = calvCTDAO.selectByDate(date);
        try {
            Date toDay = spf.parse(timeNow);
            Date viewDay = spf.parse(date);
            System.out.println(viewDay.compareTo(toDay));
            System.out.println("1s");
            if (viewDay.compareTo(toDay) < 0) {
//                check = false;
                MsgBox.alert(this, "Không thể chỉnh sửa lịch phân ca trong hôm nay và quá khứ!");
            } 
            
            else if ((viewDay.compareTo(toDay) > 0) && !listCaLvCT.isEmpty()) {
                calvCTDAO.deleteAllBydate(date);
                for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
                    for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                        if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                            NhanVien nv = new NhanVien();
                            nv = list.get(j);

                            CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                            System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                            calvCTDAO.insert(caLvCT);

                        }
                    }

                }
                MsgBox.alert(this, "Cập nhật thành công!");
            } else {
                System.out.println("Hello");
                for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
                    for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                        if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                            NhanVien nv = new NhanVien();
                            nv = list.get(j);

                            CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                            System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                            calvCTDAO.insert(caLvCT);

                        }
//if(jtbPhanCa.getValueAt(i,j)==jtbPhanCa.getValueAt(i,j+1)){}

                    }

                }
                MsgBox.alert(this, "Lưu thành công");
            }
        } catch (ParseException ex) {
            Logger.getLogger(View_QuangLyCH.class.getName()).log(Level.SEVERE, null, ex);
        }

//

    }//GEN-LAST:event_btnLuuLichPcActionPerformed

    private void jtbPhanCaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbPhanCaPropertyChange
        // TODO add your handling code here:
//        System.out.println("View.QuangLyCH.jtbPhanCaPropertyChange()");
//        CapNhatPhanCa();
    }//GEN-LAST:event_jtbPhanCaPropertyChange

    private void jtbPhanCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPhanCaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbPhanCaMouseClicked

    private void txtGhiChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGhiChuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuMouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
//        System.out.println("View.QuangLyCH.jPanel2MouseClicked()");
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jtbChoXacNhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChoXacNhanCongMouseClicked
        // TODO add your handling code here:
        int index = jtbChoXacNhanCong.getSelectedRow();
        CaLamViecCT caLamViecCT = new CaLamViecCT();
        caLamViecCT = listCaLvCT.get(index);
        CaLamViec caLamViec= new CaLamViec();
        caLamViec = caLamViecDAO.selectById(caLamViecCT.getMaCaLV());
        NhanVien nhanVien = new NhanVien();
        nhanVien = nvDAO.selectById(caLamViecCT.getMaNV());
        txtTenNV.setText(nhanVien.getHoTenNV());
        txtMaNV.setText(nhanVien.getMaNV()+"");
        txtCalamViec.setText(caLamViecCT.getMaCaLV());
        txtTgChamCong.setText(caLamViecCT.getThoiGianChamCong());
        txtTgKetThuc.setText(caLamViec.getThoiGianKetThuc());
        txtBatDau.setText(caLamViec.getThoiGianBatDau());
    }//GEN-LAST:event_jtbChoXacNhanCongMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        FillToTableCaChoXn();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            new View_QuangLyCH().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JclNgayPhanCa;
    private javax.swing.JButton btnLuuLichPc;
    private javax.swing.JButton btnXacNhanDung;
    private javax.swing.JButton btnXacNhanSai;
    private javax.swing.JButton btnXemLicPc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbChoXacNhanCong;
    private javax.swing.JTable jtbPhanCa;
    private javax.swing.JTextField txtBatDau;
    private javax.swing.JTextField txtCalamViec;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTgChamCong;
    private javax.swing.JTextField txtTgKetThuc;
    // End of variables declaration//GEN-END:variables
// In the nhan vien
    NhanVienDAO nvDAO = new NhanVienDAO();
    CaLamViecCTDAO calvCTDAO = new CaLamViecCTDAO();
    CaLamViecDAO caLamViecDAO = new CaLamViecDAO();
    public void FillToTablePhanCa() {
        System.out.println("View.QuangLyCH.FillToTablePhanCa()");
        list = nvDAO.selectAll();
        System.out.println("View.QuangLyCH.FillToTablePhanCa()" + list.size());
        modelNV.setRowCount(0);
        for (NhanVien nhanVien : list) {
            modelNV.addRow(new Object[]{nhanVien.getHoTenNV() + "-" + nhanVien.getMaNV(), false, false, false, false, false});
        }

    }
public void FillToTableCaChoXn() {
    System.out.println("View.QuangLyCH.FillToTableCaChoXn()");
        listCaLvCT = calvCTDAO.getCaLamViecChoXN();
        modelCaChoXn.setRowCount(0);
        System.out.println(Auth.user.getHoTenNV());
        for (CaLamViecCT caLamViecCT : listCaLvCT) {
            modelCaChoXn.addRow(new Object[]{Auth.user.getHoTenNV(),caLamViecCT.getMaCaLV(),caLamViecCT.getThoiGianChamCong()});
        }

    }
}
