/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CaLamViecCTDAO;
import DAO.CaLamViecDAO;
import DAO.HoaDonCTDAO;
import DAO.HoaDonDAO;
import DAO.LoaiSanPhamDAO;
import DAO.NhanVienDAO;
import Model.CaLamViec;
import Model.CaLamViecCT;
import Model.LoaiSanPham;
import Model.NhanVien;
import Model.SanPham;
import com.edysys.utils.Auth;
import com.edysys.utils.MsgBox;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class View_QuangLyCH extends javax.swing.JFrame {

    DefaultTableModel modelDoanhThu = new DefaultTableModel();
    DefaultTableModel modelNV = new DefaultTableModel();
    DefaultTableModel modelCaChoXn = new DefaultTableModel();
    List<NhanVien> list = new ArrayList<>();
    List<CaLamViecCT> listCaLvCT = new ArrayList<>();
    List<CaLamViecCT> dScaChoXn = new ArrayList<>();
    List<LoaiSanPham> listLoaiSP = new ArrayList<>();

    /**
     * Creates new form QuangLyCH
     */
    public View_QuangLyCH() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Hiển thị toàn màng hình khi open
        Image img1 = Toolkit.getDefaultToolkit().createImage("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\TGSTeam\\src\\icon\\bird.png");
        this.setIconImage(img1);
        this.setLocationRelativeTo(null);
        modelNV = (DefaultTableModel) jtbPhanCa.getModel();
        jtbPhanCa.setModel(modelNV);
        modelCaChoXn = (DefaultTableModel) jtbChoXacNhanCong.getModel();
        jtbChoXacNhanCong.setModel(modelCaChoXn);
        modelDoanhThu = (DefaultTableModel) jtbBaoCaoDoanhThu.getModel();
        jtbBaoCaoDoanhThu.setModel(modelDoanhThu);
        // FillToTableCaChoXn();
        jtbBaoCaoDoanhThu.setDefaultRenderer(Object.class, new RenderTablaPrestamos());

        jtbChoXacNhanCong.setDefaultRenderer(Object.class, new RenderTablaPrestamos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPhanCa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JclNgayPhanCa = new com.toedter.calendar.JDateChooser();
        btnXemLicPc = new javax.swing.JButton();
        btnLuuLichPc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbChoXacNhanCong = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBatDau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTgKetThuc = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtTgChamCong = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnXacNhanDung = new javax.swing.JButton();
        btnXacNhanSai = new javax.swing.JButton();
        txtCalamViec = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jlbGioCongLam = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jlbGioPhanCa = new javax.swing.JLabel();
        btnXacNhanSai1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbBaoCaoDoanhThu = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(102, 180, 223));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jtbPhanCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên + User", "Ca 1 (5)", "Ca 2 (2)", "Ca 3 (2)", "Ca 4 (2)", "Ca 5 (3.5)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPhanCa.setRowHeight(30);
        jtbPhanCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPhanCaMouseClicked(evt);
            }
        });
        jtbPhanCa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbPhanCaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPhanCa);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Ngày phân ca:");

        JclNgayPhanCa.setDateFormatString("yyyy-MM-dd");

        btnXemLicPc.setText("Xem");
        btnXemLicPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLicPcActionPerformed(evt);
            }
        });

        btnLuuLichPc.setText("Lưu lịch phân ca");
        btnLuuLichPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLichPcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JclNgayPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXemLicPc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuLichPc)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JclNgayPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXemLicPc)
                        .addComponent(btnLuuLichPc)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý phân ca", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("Chú ý: Vui lòng xác nhận chính xác, nghiêm cấm hành vi gian lận ");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yều cầu chờ xác nhận!", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jtbChoXacNhanCong.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtbChoXacNhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nhân viên", "Ca", "Thời gian chấm công", "Ngày"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbChoXacNhanCong.setGridColor(new java.awt.Color(153, 204, 255));
        jtbChoXacNhanCong.setRowHeight(25);
        jtbChoXacNhanCong.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jtbChoXacNhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbChoXacNhanCongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbChoXacNhanCong);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xác nhận công!", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ca làm việc:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ghi chú:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Thời gian chấm công:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Bắt đầu:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Kết thúc:");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        txtGhiChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGhiChuMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(txtGhiChu);

        btnXacNhanDung.setText("Đồng ý");

        btnXacNhanSai.setText("Vắng");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Thời gian thực làm / giờ phân ca:");

        jlbGioCongLam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbGioCongLam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbGioCongLam.setText("0");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("/");

        jlbGioPhanCa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbGioPhanCa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbGioPhanCa.setText("0");

        btnXacNhanSai1.setText("Cập nhật giờ làm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnXacNhanDung)
                                .addGap(18, 18, 18)
                                .addComponent(btnXacNhanSai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXacNhanSai1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCalamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel20))))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(txtTgChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(248, 248, 248))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTgKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jlbGioCongLam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlbGioPhanCa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTgKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTgChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jlbGioCongLam)
                    .addComponent(jLabel22)
                    .addComponent(jlbGioPhanCa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhanDung)
                    .addComponent(btnXacNhanSai)
                    .addComponent(btnXacNhanSai1))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Xác nhận chấm công", jPanel2);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("In thẻ nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(865, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Tìm nhân viên", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tồn kho chính xác", jPanel4);

        jTabbedPane2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtbBaoCaoDoanhThu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtbBaoCaoDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngành hàng", "Doanh thu hôm qua", "Doanh thu hôm nay", "Tăng trưởng", "Doanh thu cùng kỳ", "Doanh thu hiện tại", "Tăng trưởng & cùng kì", "Dự báo doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbBaoCaoDoanhThu.setGridColor(new java.awt.Color(153, 204, 255));
        jtbBaoCaoDoanhThu.setRowHeight(25);
        jtbBaoCaoDoanhThu.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(jtbBaoCaoDoanhThu);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-office-chart-line-stacked-icon.png"))); // NOI18N
        jButton2.setText("Xem báo cáo tăng trưởng");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mimetypes-application-vnd-ms-excel-icon.png"))); // NOI18N
        jButton3.setText("Xuất Excel");
        jButton3.setBorder(null);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print-icon.png"))); // NOI18N
        jButton4.setText("Print");
        jButton4.setBorder(null);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jTabbedPane2.addTab("Báo cáo tăng trưởng", jPanel9);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Quỹ lương");
        jLabel2.setOpaque(true);

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giờ công đã xác nhận", "Lương tạm tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane5.setViewportView(jTable1);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 51, 102))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Tổng số giờ công:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("0");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Doanh thu trung bình / giờ công:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("0");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Lợi nhuận tạm tính:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("0");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Quỹ thưởng tạm tính:");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 102));
        jLabel21.setText("Mất mát kiểm kê - Tháng");
        jLabel21.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(307, 307, 307)
                                .addComponent(jLabel21)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(531, 531, 531))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jTabbedPane2.addTab("Theo dõi lợi nhuận", jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Báo cáo tài chính", jPanel7);

        jMenu1.setText("Chức năng hệ thống");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chức năng khác");

        jMenuItem2.setText("Lịch sử chấm công");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //FillToTablePhanCa();
    }//GEN-LAST:event_formWindowOpened

    private void btnXemLicPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLicPcActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(JclNgayPhanCa.getDate());
            //calvCTDAO.selectById(date)
            listCaLvCT = calvCTDAO.selectByDate(date);
            if (listCaLvCT == null) {
                MsgBox.alert(this, "Ngày " + date + " chưa có ca làm việc!");
                FillToTablePhanCa();
            } else {
                list = nvDAO.selectAll();
                modelNV.setRowCount(0);
                for (NhanVien nhanVien : list) {
                    modelNV.addRow(new Object[]{nhanVien.getHoTenNV() + "-" + nhanVien.getMaNV(), calvCTDAO.KiemTraCaLam(date, "CA1", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA2", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA3", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA4", nhanVien.getMaNV()), calvCTDAO.KiemTraCaLam(date, "CA5", nhanVien.getMaNV())});
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(this, "Hãy lựa chọn ngày phân ca!");
        }
    }//GEN-LAST:event_btnXemLicPcActionPerformed

    private void btnLuuLichPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLichPcActionPerformed
        // TODO add your handling code here:
//        boolean check = true;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(JclNgayPhanCa.getDate());
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        SimpleDateFormat spf = new SimpleDateFormat("yyyy-MM-dd");
        listCaLvCT = calvCTDAO.selectByDate(date);
        try {
            Date toDay = spf.parse(timeNow);
            Date viewDay = spf.parse(date);
            System.out.println(viewDay.compareTo(toDay));
            System.out.println("1s");
            if (viewDay.compareTo(toDay) < 0) {
//                check = false;
                MsgBox.alert(this, "Không thể chỉnh sửa lịch phân ca trong hôm nay và quá khứ!");
            } else if ((viewDay.compareTo(toDay) == 0)) {
                if (listCaLvCT != null) {
                    calvCTDAO.deleteAllBydate(date);
                    for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
                        for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                            if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                                NhanVien nv = new NhanVien();
                                nv = list.get(j);

                                CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                                System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                                calvCTDAO.insert(caLvCT);

                            }
                        }

                    }
                    MsgBox.alert(this, "Cập nhật thành công!");
                } else {
                    for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
                        for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                            if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                                NhanVien nv = new NhanVien();
                                nv = list.get(j);

                                CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                                System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                                calvCTDAO.insert(caLvCT);

                            }
                        }

                    }
                    MsgBox.alert(this, "Lưu thành công!");
                }

            } else {
                if (listCaLvCT == null) {
                    System.out.println("Hello");
                    for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
                        for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                            if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                                NhanVien nv = new NhanVien();
                                nv = list.get(j);

                                CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                                System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                                calvCTDAO.insert(caLvCT);

                            }
                        }

                    }
                    MsgBox.alert(this, "Lưu thành công");
                } else {
                    calvCTDAO.deleteAllBydate(date);
                    for (int i = 1; i < jtbPhanCa.getColumnCount(); i++) {
                        for (int j = 0; j < jtbPhanCa.getRowCount(); j++) {
                            if ((boolean) jtbPhanCa.getValueAt(j, i) == true) {
                                NhanVien nv = new NhanVien();
                                nv = list.get(j);

                                CaLamViecCT caLvCT = new CaLamViecCT("CA" + i, nv.getMaNV(), date);
                                System.out.println("View.QuangLyCH.btnLuuLichPcActionPerformed() Insert");
                                calvCTDAO.insert(caLvCT);

                            }
                        }

                    }
                    MsgBox.alert(this, "Cập nhật thành công!");
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(View_QuangLyCH.class.getName()).log(Level.SEVERE, null, ex);
        }

//

    }//GEN-LAST:event_btnLuuLichPcActionPerformed

    private void jtbPhanCaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbPhanCaPropertyChange
        // TODO add your handling code here:
//        System.out.println("View.QuangLyCH.jtbPhanCaPropertyChange()");
//        CapNhatPhanCa();
    }//GEN-LAST:event_jtbPhanCaPropertyChange

    private void jtbPhanCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPhanCaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbPhanCaMouseClicked

    private void txtGhiChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGhiChuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuMouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
//        System.out.println("View.QuangLyCH.jPanel2MouseClicked()");
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jtbChoXacNhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbChoXacNhanCongMouseClicked
        // TODO add your handling code here:
        int index = jtbChoXacNhanCong.getSelectedRow();
        CaLamViecCT caLamViecCT = new CaLamViecCT();
        caLamViecCT = listCaLvCT.get(index);
        CaLamViec caLamViec = new CaLamViec();
        caLamViec = caLamViecDAO.selectById(caLamViecCT.getMaCaLV());
        NhanVien nhanVien = new NhanVien();
        nhanVien = nvDAO.selectById(caLamViecCT.getMaNV());
        txtTenNV.setText(nhanVien.getHoTenNV());
        txtMaNV.setText(nhanVien.getMaNV() + "");
        txtCalamViec.setText(caLamViecCT.getMaCaLV());
        txtTgChamCong.setText(caLamViecCT.getThoiGianChamCong());
        txtTgKetThuc.setText(caLamViec.getThoiGianKetThuc());
        txtBatDau.setText(caLamViec.getThoiGianBatDau());
    }//GEN-LAST:event_jtbChoXacNhanCongMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        FillToTableCaChoXn();
        NhanVien nv = new NhanVien();
        nv = Auth.user;
        // Hiển thị tên nhân viên ở Bottom màng hình

        /*
       - Hiển thị form chấm công
       + điều kiện 1: Nhân viên có ca làm việc
       + điều kiện 2: nhân viên có ca chưa chấm
         */
        // Giải quyết diều kiện 1: Tìm kiếm CaLamViecCT với diều 2 tham số (MaNV,Ngay), kết quả khác null => Nhân viên có ca làm việc
        // Giải quyết điều kiện 2: Lấy ThoiGianChamCong nếu trả về null => nhân viên chưa chấm công
        CaLamViecCTDAO dao = new CaLamViecCTDAO();
        List<CaLamViecCT> list = new ArrayList<>();
        list = dao.selectByDateAndMaNV(LayNgay(), nv.getMaNV());
        if (list.size() > 0) {
            for (CaLamViecCT caLamViecCT : list) {
                if (caLamViecCT.getThoiGianChamCong() == null) {
                    ChamCong chamCong_View = new ChamCong();
                    try {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                        chamCong_View.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                    };
                    chamCong_View.setLocationRelativeTo(null);
                    return;
                }
            }
        }


    }//GEN-LAST:event_formComponentShown

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        View_LichSuChamCong view_LichSuChamCong = new View_LichSuChamCong();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            view_LichSuChamCong.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FillToTableBaoCaoDoanhThu();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_QuangLyCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            new View_QuangLyCH().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JclNgayPhanCa;
    private javax.swing.JButton btnLuuLichPc;
    private javax.swing.JButton btnXacNhanDung;
    private javax.swing.JButton btnXacNhanSai;
    private javax.swing.JButton btnXacNhanSai1;
    private javax.swing.JButton btnXemLicPc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbGioCongLam;
    private javax.swing.JLabel jlbGioPhanCa;
    private javax.swing.JTable jtbBaoCaoDoanhThu;
    private javax.swing.JTable jtbChoXacNhanCong;
    private javax.swing.JTable jtbPhanCa;
    private javax.swing.JTextField txtBatDau;
    private javax.swing.JTextField txtCalamViec;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTgChamCong;
    private javax.swing.JTextField txtTgKetThuc;
    // End of variables declaration//GEN-END:variables
// In the nhan vien
    NhanVienDAO nvDAO = new NhanVienDAO();
    CaLamViecCTDAO calvCTDAO = new CaLamViecCTDAO();
    CaLamViecDAO caLamViecDAO = new CaLamViecDAO();
    LoaiSanPhamDAO loaiSanPhamDAO = new LoaiSanPhamDAO();
    HoaDonDAO hoaDonDAO = new HoaDonDAO();
    HoaDonCTDAO hoaDonCTDAO = new HoaDonCTDAO();

    public void FillToTablePhanCa() {
        list = nvDAO.selectAll();
        modelNV.setRowCount(0);
        for (NhanVien nhanVien : list) {
            modelNV.addRow(new Object[]{nhanVien.getHoTenNV() + "-" + nhanVien.getMaNV(), false, false, false, false, false});
        }

    }

    public void FillToTableCaChoXn() {
        listCaLvCT = calvCTDAO.getCaLamViecChoXN();
        modelCaChoXn.setRowCount(0);
        System.out.println(Auth.user.getHoTenNV());
        for (CaLamViecCT caLamViecCT : listCaLvCT) {
            modelCaChoXn.addRow(new Object[]{Auth.user.getHoTenNV(), caLamViecCT.getMaCaLV(), caLamViecCT.getThoiGianChamCong(), caLamViecCT.getNgay()});
        }

    }

    public void FillToTableBaoCaoDoanhThu() {
        Calendar cal = Calendar.getInstance();
        DecimalFormat df = new DecimalFormat("#.##");
        listLoaiSP = loaiSanPhamDAO.selectAll();
        modelDoanhThu.setRowCount(0);
        float tongDoanhThuHomQua = 0;

        float tongDoanhThuHomNay = 0;
        float tongTangTruongNgay = 0;
        float tong = 0;
        float tongDoanhThuCungKy = 0;
        float tongDoanhThuHienTai = 0;
        float tongTangTruongCungKy = 0;
        float tongDuBaoDoanhThu = 0;
        for (LoaiSanPham loaiSanPham : listLoaiSP) {
            float doanhThuHomQua = hoaDonDAO.getDoanhThuTheoNganhHang(loaiSanPham.getMaLoaiSP(), getYesterday() + " 00:00:00", getYesterday() + " 23:59:00");
            tongDoanhThuHomQua = tongDoanhThuHomQua + doanhThuHomQua;
            float doanhThuHomNay = hoaDonDAO.getDoanhThuTheoNganhHang(loaiSanPham.getMaLoaiSP(), LayNgay() + " 00:00:00", LayNgay() + " 23:59:00");
            tongDoanhThuHomNay = tongDoanhThuHomNay + doanhThuHomNay;
            float tangTruongNgay = ((doanhThuHomNay - doanhThuHomQua) / doanhThuHomQua) * 100;
            tongTangTruongNgay = tongTangTruongNgay + tangTruongNgay;
            float doanhThuCungKy = hoaDonCTDAO.getDoanhThuCungKy(loaiSanPham.getMaLoaiSP(), getNgayNayThangTruoc() + " 00:00:00");
            tongDoanhThuCungKy = tongDoanhThuCungKy + doanhThuCungKy;
            float doanhThuHienTai = hoaDonCTDAO.getDoanhThuHienTai(loaiSanPham.getMaLoaiSP(), LayNgay() + " 00:00:00");
            tongDoanhThuHienTai = tongDoanhThuHienTai + doanhThuHienTai;
            float tangTruongCungKy = ((doanhThuHienTai - doanhThuCungKy) / doanhThuCungKy) * 100;
            tongTangTruongCungKy = tongTangTruongCungKy + tangTruongCungKy;
            float duBaoDoanhThu = doanhThuHienTai / Float.parseFloat(String.valueOf(cal.get(Calendar.DAY_OF_MONTH))) * getSoNgayTrongThang();
            tongDuBaoDoanhThu = tongDuBaoDoanhThu + duBaoDoanhThu;
            modelDoanhThu.addRow(new Object[]{loaiSanPham.getTenLoaiSP(), df.format(doanhThuHomQua), df.format(doanhThuHomNay), df.format(tangTruongNgay) + " %", df.format(doanhThuCungKy), df.format(doanhThuHienTai), df.format(tangTruongCungKy) + " %", duBaoDoanhThu});
        }
        modelDoanhThu.addRow(new Object[]{"Tổng kết:", tongDoanhThuHomQua, tongDoanhThuHomNay, tongTangTruongNgay, tongDoanhThuCungKy, df.format(tongDoanhThuHienTai), tongTangTruongCungKy, df.format(tongDuBaoDoanhThu)});

    }

    public String LayNgay() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        return timeNow;
    }

    public int getSoNgayTrongThang() {
        Calendar cal = Calendar.getInstance();

        YearMonth yearMonthObject = YearMonth.of(cal.get(Calendar.YEAR), cal.get(Calendar.MONTH) + 1);
        int daysInMonth = yearMonthObject.lengthOfMonth();
        return daysInMonth;
    }

    public String getYesterday() {
        DateFormat dateFormat = new SimpleDateFormat("dd");
        Calendar cal = Calendar.getInstance();
        String yesterday = "";
        String year = String.valueOf(cal.get(Calendar.YEAR));
        String month = String.valueOf(cal.get(Calendar.MONTH) + 1);
        String ngayHomQua = String.valueOf(cal.get(Calendar.DAY_OF_MONTH) - 1);
        yesterday = year + "-" + month + "-" + ngayHomQua;
        return yesterday;
    }

    public String getNgayNayThangTruoc() {
        DateFormat dateFormat = new SimpleDateFormat("dd");
        Calendar cal = Calendar.getInstance();
        String yesterday = "";
        String year = String.valueOf(cal.get(Calendar.YEAR));
        String month = String.valueOf(cal.get(Calendar.MONTH));
        String ngayHomQua = String.valueOf(cal.get(Calendar.DAY_OF_MONTH) - 1);
        yesterday = year + "-" + month + "-" + ngayHomQua;
        return yesterday;
    }

    public String Lay1Thang() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        return timeNow;
    }

    public String Lay1Nam() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        String timeNow = dateFormat.format(cal.getTime());
        return timeNow;
    }

    public class RenderTablaPrestamos extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            c.setBackground(row % 2 == 0 ? Color.LIGHT_GRAY : Color.WHITE);
            return c;
        }

    }
}
